initialize-venv: &initialize-venv
  name: Initialize Virtual Environment
  command: |
    python -m virtualenv ../venv || python -m venv ../venv
    . ../venv/bin/activate

ci-steps: &ci-steps
  steps:
    - checkout
    - run:
        <<: *initialize-venv
    - run:
        name: Run the tests
        command: |
          . ../venv/bin/activate
          pip install tox
          tox -e $TEST_TOX_ENV

version: 2
jobs:
  python27:
    docker:
      - image: circleci/python:2.7.14-jessie
    environment:
     - TEST_TOX_ENV: "py27"
    <<: *ci-steps

  python35:
    docker:
      - image: circleci/python:3.5.4-jessie
    environment:
     - TEST_TOX_ENV: "py35"
    <<: *ci-steps

  python36:
    docker:
      - image: circleci/python:3.6.3-jessie
    environment:
     - TEST_TOX_ENV: "py36"
    <<: *ci-steps

workflows:
  version: 2
  test:
    jobs:
      - python27
      - python35
      - python36
